version: '3'

services:
  canksweb:
    image: registry.canks.dev/canksweb:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.canksweb.rule=Host(`canks.dev`)"
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_SHOW_LOGGER=false
    networks:
      - traefik
networks:
  traefik:
    external: true